services:
  database:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_DATABASE=sustaintracker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - api
  api:
    environment:
      - NODE_ENV=development
    build:
      context: ./api
    ports:
      - "8080:8080"
    links:
      - "database"
    networks:
      - nginx
      - api
  nginx:
      restart: always
      build:
          context: .
          dockerfile: nginx/Dockerfile
      ports:
          - "80:80"
      networks:
      - nginx

networks:
  nginx:
  api: